export const offerApi = [
   {
      id: 1,
      title: "Tasty Thursdays",
      discount: 15,
      image: "./images/o1.jpg",
   },
   {
      id: 2,
      title: "Pizza Days",
      discount: 15,
      image: "./images/o1.jpg",
   },
];

export const menuApi = [
   {
      id: 1,
      name: "Delicious Pizza",
      img: "images/f1.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 20,
      prePrice: 22,
      category: "Pizza",
   },
   {
      id: 2,
      name: "Delicious Burger",
      img: "images/f2.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 15,
      prePrice: 16,
      category: "Burger",
   },
   {
      id: 3,
      name: "Delicious Pizza",
      img: "images/f3.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 17,
      prePrice: 18,
      category: "Pizza",
   },
   {
      id: 4,
      name: "Delicious Pasta",
      img: "images/f4.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 18,
      prePrice: 19.5,
      category: "Pasta",
   },
   {
      id: 5,
      name: "French Fries",
      img: "images/f5.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 10,
      prePrice: 12,
      category: "Fries",
   },
   {
      id: 6,
      name: "Delicious Pizza",
      img: "images/f6.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 15,
      prePrice: 16.4,
      category: "Pizza",
   },
   {
      id: 7,
      name: "Tasty Burger",
      img: "images/f7.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 12,
      prePrice: 15,
      category: "Burger",
   },
   {
      id: 8,
      name: "Tasty Burger",
      img: "images/f8.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 14,
      prePrice: 16,
      category: "Burger",
   },
   {
      id: 9,
      name: "Delicious Pasta",
      img: "images/f9.png",
      dec: "Veniam debitis quaerat officiis quasi cupiditate quo, quisquam velit, magnam voluptatem repellendus sed eaque",
      price: 10,
      prePrice: 11,
      category: "Pasta",
   },
];
export const chefsApi = [
   {
      id: 1,
      name: "Emily Bennett",
      image: "./images/chef-1.jpg",
      position: "Executive Chef",
      about: "Passionate about bold flavors and global inspiration. A simple person.",
   },
   {
      id: 2,
      name: "Carlos Rodriguez",
      image: "./images/chef-2.jpg",
      position: "CEO, Co Founder",
      about: "Respects heritage, crafts with precision. Ambitious workaholic",
   },
   {
      id: 3,
      name: "Sophia Nguyen",
      image: "./images/chef-3.jpg",
      position: "Chef Cook",
      about: "Creates artistic desserts, a feast for eyes and taste.",
   },
   {
      id: 4,
      name: "Alex Thompson",
      image: "./images/chef-4.jpg",
      position: "Head Chef",
      about: "I am an ambitious workaholic, but apart from that, pretty simple person",
   },
];
